### ISSUE TITLE
Invalid import assertion

### ISSUE THREAD

**Issue by nicolo-ribaudo** [polymorpher/burner#1]
Hi!

I noticed that you are using an `integrity` assertion, that is invalid and it's currently being ignored by browsers.

We are updating the import assertions behavior to throw on unknown ones, so you might want to remove it.

https://github.com/polymorpher/burner/blob/0baf45f0ad01ab83b41e7ae4a902088499037363/charts/src/Data.tsx#L3

**Comment by polymorpher** [comment]
thanks, fixed
