### ISSUE TITLE
Allowance error, but allowance was granted to max.

### ISSUE THREAD

**Issue by Severino** [polymorpher/burner#2]
Hi, I tried to use the website, but I received the error:

```json
testTx Error Error: Internal JSON-RPC error.
{
  "code": 3,
  "message": "execution reverted: ERC20: transfer amount exceeds allowance"
}
```
_What did I do?_
1. I properly executed the allowance transaction with 'unlimited' spending.
2. I also verified that by calling the allowance method on the depegged USDC contract
on the current burner contract: 0x8Ba8fa550861fCA4615a82E2bc9cf9C197Cd54ec

_What could be the issue?_
Maybe the contract was not updated correctly?

**Comment by polymorpher** [comment]
Round has not started and the (old) burner is not authorized to use any fund

**Comment by Severino** [comment]
Thanks for the quick reply.
Is there maybe a way to indicate that? 
It's not very clear for new users and I didn't find any information about it.

**Comment by polymorpher** [comment]
Yes, I agree, will fix
